esphome:
  name: wt32-eth01
  friendly_name: Electrical Box
  min_version: 2025.8.0
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16
# Optional manual IP
  manual_ip:
    static_ip: 192.168.1.126
    gateway: 192.168.1.1
    subnet: 254.255.255.0

# Enable Home Assistant API
api:
  port: 6053

# Browser access
web_server:
  port: 80

safe_mode:
  disabled: false

ota:
  - platform: esphome
    id: ota_esphome
    password: XXX

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

external_components:
    - source: github://tube0013/esphome-stream-server-v2

# Set baud_rate to 0 to disable logging via UART.
logger:
    baud_rate: 0

uart:
  id: uart_bus
  rx_pin: GPIO3
  # Laut das Holley-Dtz541-Serie Benutzerhandbuch:
  # "konstante Datenrate ist 9600 Baud und die Zeichenkodierung ist 8-N-1."
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

stream_server:
   id: ss
   uart_id: uart_bus
   port: 2001

binary_sensor:
  - id: stream_server_client_connection
    name: stream_server_client_connection
    platform: stream_server
    stream_server: ss
